name: "Cherry-pick from rc to develop"

on:
  pull_request:
    branches:
      - release/candidate
    types:
      - closed

jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Append -cherry-pick to branch name
        id: extract
        run: |
          set -x
          PR_BRANCH="${{ github.event.pull_request.head.ref }}"
          NEW_BRANCH_NAME="${PR_BRANCH}-cherry-pick"
          echo "New branch name: $NEW_BRANCH_NAME"
          echo "newBranchName=$NEW_BRANCH_NAME" >> $GITHUB_ENV

      - uses: fregante/setup-git-user@v2

      - name: Cherry-pick commits
        id: cherry
        run: |
          set -x
          git fetch origin develop:develop
          git checkout -b ${{ env.newBranchName }} develop
          # Cherry-picking the last commit on the base branch
          OUTPUT=$(git cherry-pick ${{ github.event.pull_request.merge_commit_sha }} --strategy-option theirs || true)
          CONFLICTS=$(echo "$OUTPUT" | grep 'CONFLICT' || echo "")
          if [ -n "$CONFLICTS" ]; then
              git add .
              git cherry-pick --continue || true
          fi
          git push origin ${{ env.newBranchName }} || (echo "Failed to push to origin" && exit 1)
          
          if [ -n "$CONFLICTS" ]; then
              echo -e "---- \n\n ⚠️ Conflicts during cherry-pick:\n$CONFLICTS\n\n" > CONFLICTS_MESSAGE
          else
              echo "" > CONFLICTS_MESSAGE
          fi
          echo "conflictsMessage=$(cat CONFLICTS_MESSAGE)" >> $GITHUB_ENV

      - name: Create PR
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_BRANCH: ${{ env.newBranchName }}
          PR_ASSIGNEE: ${{ github.event.pull_request.user.login }}
          PR_BODY: "${{ format('Cherry pick from the original PR: \n- #{0}\n\n{1}{2}', github.event.pull_request.number, env.conflictsMessage, github.event.pull_request.body) }}"
        run: gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base develop --head $PR_BRANCH --label "cherry-pick" --assignee "$PR_ASSIGNEE"
